name: calendar_and_map_tutorial_in_flutter
description: "A Flutter application with calendar and map features."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Calendar packages
  infinite_calendar_view: ^2.5.4
  calendar_view: ^1.4.0
  easy_date_timeline: ^2.0.9

  # Maps
  google_maps_flutter: ^2.12.1
  
  # Navigation
  go_router: ^15.1.2

  # Utilities
  equatable: ^2.0.7
  dartz: ^0.10.1
  http: ^1.4.0
  intl: ^0.19.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  freezed: ^3.0.6
  json_serializable: ^6.9.5


flutter:

  uses-material-design: true
